server:
  port: 8080
  servlet:
    context-path: /elp
spring:
  datasource:
    url: "jdbc:mysql://mysql-11d76882-binhball.k.aivencloud.com:11528/defaultdb"
    username: avnadmin
    password: AVNS_MyhVYKtj6VagnO9YkUo
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
  data:
    redis:
      host: localhost
      port: 6379
      connect-timeout:
jwt:
  signerKey: "b4ISo6+PT1fY8eppQ564SXabONN945cjuPYa0mTOmPrThHVxEnH7+xxE5RFJCqtk"
